Added PDF feature + some button changes
AndradeChris/fullstack-domHotel pull request #72
Opened 2023-03-18 19:12 UTC by DeboraAlmeida

Generatinhg reserve resume PDF. Also added 'Imprimir Reserva' button and some change in 'Confirmar' button going on Alterar Reserva button

2023-03-20 14:36 UTC, LarissaCordovil approved these changes

2023-03-31 13:26 UTC, LarissaCordovil approved these changes

2023-03-31 13:27 UTC, LarissaCordovil approved these changes

2023-04-05 18:00 UTC, Flaviano-Rodrigues requested changes
Resolver os conflitos antes de subir alguma outra alteração.

2023-04-07 19:35 UTC, merged