Coupon 2
AndradeChris/fullstack-domHotel pull request #77
Opened 2023-03-31 13:28 UTC by LarissaCordovil

2023-03-31 18:01 UTC, Flaviano-Rodrigues requested changes
Há arquivos no frontend em javascript.

2023-04-03 21:19 UTC, Flaviano-Rodrigues requested changes
**OBS:** essas coisas que estou pedindo para você mudar normalmente eu deixo passar e mudo quando eu vou subir algum pr meu. Porém como estou sem pc, e por isso estou requisitando para você mesma fazer as alterações.

- a prop "totalValue" é claramente uma string. Não tem a necessidade de coloca-la como "any".

o "event" na linha 17 não precisa ser "any" pois você sabe exatamente o valor que está vindo. Como estou sem pc não consigo colocar um exemplo aqui para você, porém se você for em qualquer arquivo typescript do projeto que pega evento de algum elemento você vai conseguir um ótimo exemplo de como fazer, daí é só replicar e remover esse "any" feioso daí.

2023-04-10 17:01 UTC, Flaviano-Rodrigues approved these changes

2023-04-16 18:48 UTC, AndradeChris approved these changes

2023-04-16 18:48 UTC, merged